apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-api
spec:
  selector:
    matchLabels:
      app: greetings-api
  replicas: 1
  template:
    metadata:
      labels:
        app: greetings-api
    spec:
      containers:
      - name: greetings-api
        image: greetings-api:latest
        imagePullPolicy: Never  # Because this is a local image
        ports:
        - containerPort: 5555
